# StrayLight OS Calamares Installer Settings
# SPDX-License-Identifier: GPL-3.0-or-later

modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules, /usr/lib/calamares/modules ]

instances:
  - id: straylight-hwtest
    module: shellprocess
    config: straylight-hwtest.conf
  - id: straylight-postinstall
    module: shellprocess
    config: straylight-postinstall.conf

sequence:
  - show:
      - welcome
      - locale
      - partition
      - keyboard
      - users
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - packages
      - shellprocess@straylight-hwtest
      - initramfscfg
      - initramfs
      - grubcfg
      - bootloader
      - shellprocess@straylight-postinstall
  - show:
      - finished

branding: straylight

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false
disable-cancel-during-exec: true

hide-back-and-next-during-exec: true

quit-at-end: false
