#!/bin/sh
set -eu

case " $* " in
    *" --efi-directory="*)
        echo "straylight-grub-install: running EFI GRUB install with --no-nvram; Calamares will install the fallback loader" >&2
        exec /usr/sbin/grub-install --no-nvram "$@"
        ;;
esac

exec /usr/sbin/grub-install "$@"
