# StrayLight OS Calamares Installer Settings
# SPDX-License-Identifier: GPL-3.0-or-later

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - partition
      - straylight-hwscan
      - straylight-drivers
      - users
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - packages
      - straylight-hwtest
      - initramfscfg
      - initramfs
      - grubcfg
      - bootloader
      - straylight-postinstall
  - show:
      - finished

branding: straylight

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false
disable-cancel-during-exec: true

hide-back-and-next-during-exec: true

quit-at-end: false
