# StrayLight OS bootloader configuration
# SPDX-License-Identifier: GPL-3.0-or-later

efiBootLoader: grub
efiBootloaderId: "StrayLight OS"
installEFIFallback: true

grubInstall: /usr/sbin/grub-install
grubMkconfig: /usr/sbin/grub-mkconfig
grubCfg: /boot/grub/grub.cfg
grubProbe: /usr/sbin/grub-probe
efiBootMgr: /usr/bin/efibootmgr

kernelParams:
    - quiet
