# Locale module configuration

region: "NorthAmerica"
zone: "New_York"

localeGenPath: /etc/locale.gen

geoip:
    style: "json"
    url: "https://geoip.straylight.dev/json"
    selector: ""

adjustLiveTimezone: true

useSystemTimezone: true
