# Users module configuration

defaultGroups:
    - name: users
    - name: sudo
    - name: cdrom
    - name: floppy
    - name: audio
    - name: dip
    - name: video
    - name: plugdev
    - name: netdev
    - name: bluetooth
    - name: lpadmin
    - name: scanner
    - name: straylight
      must_exist: false
      system: true

autologinGroup: autologin

doAutologin: false

sudoersGroup: sudo

setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2

allowWeakPasswords: false
allowWeakPasswordsDefault: false

userShell: /bin/bash

hostname:
    location: EtcFile
    writeHostsFile: true
    template: "straylight-${cpu}"
    forbidden_names:
        - localhost
        - localhost.localdomain
