/**
 * StrayLight Quota — Configuration Parser
 *
 * Reads /etc/straylight/quotas.conf with per-app resource budgets.
 *
 * Format:
 *   [default]
 *   cpu_percent = 25
 *   ram_bytes = 2147483648
 *   ...
 *
 *   [app:firefox]
 *   cpu_percent = 50
 *   ram_bytes = 4294967296
 *   vram_bytes = 1073741824
 *   ...
 *
 *   [policy]
 *   warn_threshold = 80
 *   throttle_threshold = 95
 *   kill_threshold = 100
 *   enforcement = on
 */
#pragma once

#include "straylight/result.h"

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <limits>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>

namespace straylight::quota {

/** Resource budget for a single application. */
struct ResourceQuota {
    double   cpu_percent{100.0};           // 0-100 per-core, or total %
    uint64_t ram_bytes{0};                  // 0 = unlimited
    uint64_t vram_bytes{0};                 // VPU VRAM budget
    double   gpu_compute_percent{100.0};    // mesh GPU %
    uint64_t disk_iops{0};                  // 0 = unlimited
    uint64_t net_bandwidth{0};              // bytes/sec, 0 = unlimited
    double   compositor_fps{0.0};           // 0 = unlimited
};

/** Enforcement action thresholds. */
struct EnforcementPolicy {
    double warn_threshold{80.0};       // % of quota to emit warning
    double throttle_threshold{95.0};   // % of quota to throttle
    double kill_threshold{105.0};      // % of quota to kill
    bool   enforcement_enabled{true};
};

class QuotaConfig {
public:
    static constexpr const char* DEFAULT_PATH =
        "/etc/straylight/quotas.conf";

    explicit QuotaConfig(std::string path = DEFAULT_PATH)
        : path_(std::move(path)) {}

    /** Load configuration from disk. */
    VoidResult<> load() {
        std::lock_guard<std::mutex> lock(mu_);
        std::ifstream in(path_);
        if (!in) {
            // If config doesn't exist, use defaults
            default_quota_ = ResourceQuota{};
            policy_ = EnforcementPolicy{};
            return VoidResult<>::ok();
        }

        std::string line;
        std::string current_section;
        std::string current_app;

        while (std::getline(in, line)) {
            // Strip comments and whitespace
            auto comment_pos = line.find('#');
            if (comment_pos != std::string::npos)
                line = line.substr(0, comment_pos);
            line = trim(line);
            if (line.empty()) continue;

            // Section header
            if (line.front() == '[' && line.back() == ']') {
                current_section = line.substr(1, line.size() - 2);
                current_app.clear();

                if (current_section.substr(0, 4) == "app:") {
                    current_app = current_section.substr(4);
                    if (app_quotas_.find(current_app) == app_quotas_.end()) {
                        // Start from default quota
                        app_quotas_[current_app] = default_quota_;
                    }
                }
                continue;
            }

            // Key = value
            auto eq_pos = line.find('=');
            if (eq_pos == std::string::npos) continue;

            std::string key = trim(line.substr(0, eq_pos));
            std::string val = trim(line.substr(eq_pos + 1));

            if (current_section == "default") {
                apply_quota_field(default_quota_, key, val);
            } else if (current_section == "policy") {
                apply_policy_field(policy_, key, val);
            } else if (!current_app.empty()) {
                apply_quota_field(app_quotas_[current_app], key, val);
            }
        }

        return VoidResult<>::ok();
    }

    /** Save current configuration to disk. */
    VoidResult<> save() const {
        std::lock_guard<std::mutex> lock(mu_);
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::create_directories(fs::path(path_).parent_path(), ec);

        std::ofstream out(path_, std::ios::trunc);
        if (!out) return VoidResult<>::error("cannot write " + path_);

        out << "# StrayLight Quota Configuration\n"
            << "# Generated by straylight-quotad\n\n";

        // Default section
        out << "[default]\n";
        write_quota(out, default_quota_);
        out << "\n";

        // Policy section
        out << "[policy]\n"
            << "warn_threshold = " << policy_.warn_threshold << "\n"
            << "throttle_threshold = " << policy_.throttle_threshold << "\n"
            << "kill_threshold = " << policy_.kill_threshold << "\n"
            << "enforcement = "
            << (policy_.enforcement_enabled ? "on" : "off") << "\n\n";

        // Per-app sections
        for (const auto& [app, quota] : app_quotas_) {
            out << "[app:" << app << "]\n";
            write_quota(out, quota);
            out << "\n";
        }

        return VoidResult<>::ok();
    }

    /** Get quota for a specific app (falls back to default). */
    ResourceQuota get_quota(const std::string& app) const {
        std::lock_guard<std::mutex> lock(mu_);
        auto it = app_quotas_.find(app);
        if (it != app_quotas_.end()) return it->second;
        return default_quota_;
    }

    /** Set quota for a specific app. */
    void set_quota(const std::string& app, const ResourceQuota& q) {
        std::lock_guard<std::mutex> lock(mu_);
        app_quotas_[app] = q;
    }

    /** Get the default quota. */
    ResourceQuota get_default() const {
        std::lock_guard<std::mutex> lock(mu_);
        return default_quota_;
    }

    /** Get enforcement policy. */
    EnforcementPolicy get_policy() const {
        std::lock_guard<std::mutex> lock(mu_);
        return policy_;
    }

    /** Set enforcement policy. */
    void set_policy(const EnforcementPolicy& p) {
        std::lock_guard<std::mutex> lock(mu_);
        policy_ = p;
    }

    /** List all apps with explicit quotas. */
    std::vector<std::string> list_apps() const {
        std::lock_guard<std::mutex> lock(mu_);
        std::vector<std::string> apps;
        apps.reserve(app_quotas_.size());
        for (const auto& [app, _] : app_quotas_) apps.push_back(app);
        std::sort(apps.begin(), apps.end());
        return apps;
    }

private:
    std::string path_;
    mutable std::mutex mu_;
    ResourceQuota default_quota_;
    EnforcementPolicy policy_;
    std::unordered_map<std::string, ResourceQuota> app_quotas_;

    static std::string trim(const std::string& s) {
        size_t start = s.find_first_not_of(" \t\r\n");
        if (start == std::string::npos) return "";
        size_t end = s.find_last_not_of(" \t\r\n");
        return s.substr(start, end - start + 1);
    }

    static void apply_quota_field(ResourceQuota& q,
                                   const std::string& key,
                                   const std::string& val) {
        try {
            if (key == "cpu_percent")         q.cpu_percent = std::stod(val);
            else if (key == "ram_bytes")      q.ram_bytes = std::stoull(val);
            else if (key == "vram_bytes")     q.vram_bytes = std::stoull(val);
            else if (key == "gpu_compute_percent") q.gpu_compute_percent = std::stod(val);
            else if (key == "disk_iops")      q.disk_iops = std::stoull(val);
            else if (key == "net_bandwidth")  q.net_bandwidth = std::stoull(val);
            else if (key == "compositor_fps") q.compositor_fps = std::stod(val);
        } catch (...) {
            // Ignore malformed values
        }
    }

    static void apply_policy_field(EnforcementPolicy& p,
                                    const std::string& key,
                                    const std::string& val) {
        try {
            if (key == "warn_threshold")     p.warn_threshold = std::stod(val);
            else if (key == "throttle_threshold") p.throttle_threshold = std::stod(val);
            else if (key == "kill_threshold")     p.kill_threshold = std::stod(val);
            else if (key == "enforcement")        p.enforcement_enabled = (val == "on" || val == "1" || val == "true");
        } catch (...) {}
    }

    static void write_quota(std::ofstream& out, const ResourceQuota& q) {
        out << "cpu_percent = " << q.cpu_percent << "\n"
            << "ram_bytes = " << q.ram_bytes << "\n"
            << "vram_bytes = " << q.vram_bytes << "\n"
            << "gpu_compute_percent = " << q.gpu_compute_percent << "\n"
            << "disk_iops = " << q.disk_iops << "\n"
            << "net_bandwidth = " << q.net_bandwidth << "\n"
            << "compositor_fps = " << q.compositor_fps << "\n";
    }
};

} // namespace straylight::quota
