// services/nerve/irq_monitor.h
// Monitor interrupt rates, detect storms, and track distribution history.
#pragma once

#include "irq_mapper.h"

#include <straylight/result.h>

#include <chrono>
#include <cstdint>
#include <map>
#include <mutex>
#include <string>
#include <vector>

namespace straylight {

/// A single data point in IRQ rate history.
struct IrqSample {
    std::chrono::steady_clock::time_point timestamp;
    uint64_t count;
    double rate_per_second;
};

/// Alert generated by the monitor.
struct IrqAlert {
    std::chrono::system_clock::time_point timestamp;
    uint32_t irq_number;
    std::string device_name;
    std::string message;
    enum class Severity { Info, Warning, Critical } severity;
};

/// Monitors interrupt rates, detects storms and imbalances.
class IrqMonitor {
public:
    IrqMonitor();

    /// Take a sample — poll /proc/interrupts and compute rates.
    Result<void, std::string> sample();

    /// Get the current rate (interrupts/sec) for a specific IRQ.
    Result<double, std::string> get_rate(uint32_t irq) const;

    /// Get all IRQs sorted by rate (highest first).
    std::vector<std::pair<uint32_t, double>> get_rates_sorted() const;

    /// Get rate history for a specific IRQ.
    std::vector<IrqSample> get_history(uint32_t irq, size_t max_samples = 60) const;

    /// Get all pending alerts (and clear them).
    std::vector<IrqAlert> get_and_clear_alerts();

    /// Get all alerts without clearing.
    std::vector<IrqAlert> get_alerts() const;

    /// Check if any IRQ is currently storming.
    bool is_storm_detected() const;

    /// Get per-CPU interrupt distribution percentages.
    std::map<uint32_t, double> get_cpu_distribution() const;

    /// Set the storm detection threshold (interrupts per second).
    void set_storm_threshold(uint64_t threshold);

    /// Set the imbalance ratio threshold for alerting.
    void set_imbalance_threshold(double ratio);

    /// Set maximum history samples to retain per IRQ.
    void set_max_history(size_t max);

private:
    /// Detect storms and imbalances from the latest sample.
    void detect_anomalies();

    /// Add an alert.
    void add_alert(uint32_t irq, const std::string& device,
                   const std::string& message, IrqAlert::Severity severity);

    mutable std::mutex mu_;

    /// Previous sample counts per IRQ (for computing deltas).
    std::map<uint32_t, uint64_t> prev_counts_;

    /// Previous sample timestamp.
    std::chrono::steady_clock::time_point prev_time_;

    /// Current rates per IRQ (interrupts/second).
    std::map<uint32_t, double> current_rates_;

    /// Device name cache per IRQ.
    std::map<uint32_t, std::string> device_names_;

    /// Rate history per IRQ.
    std::map<uint32_t, std::vector<IrqSample>> history_;

    /// Pending alerts.
    std::vector<IrqAlert> alerts_;

    /// Last emitted alert by stable alert key, retained even after alerts_ is drained.
    std::map<std::string, std::chrono::system_clock::time_point> last_alert_times_;

    /// Per-CPU total counts for distribution analysis.
    std::map<uint32_t, uint64_t> cpu_totals_;

    /// Configuration.
    uint64_t storm_threshold_ = 100000;
    double imbalance_threshold_ = 10.0;
    size_t max_history_ = 3600;  // 1 hour at 1 sample/sec

    /// Whether the first sample has been taken.
    bool initialized_ = false;
};

} // namespace straylight
