# Shared version variables derived from project()
set(STRAYLIGHT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(STRAYLIGHT_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(STRAYLIGHT_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(STRAYLIGHT_VERSION "${PROJECT_VERSION}")

# SO version: major version for ABI compatibility
set(STRAYLIGHT_SO_VERSION ${PROJECT_VERSION_MAJOR})
